### PR TITLE
delete unnecessary symbol on line 38

### PR DESCRIPTION
**Pull request by EmbraceLife**

### CODE REVIEW

**Comment by shiffman** [comment]
thanks!

**Comment by EmbraceLife** [comment]
You are very welcome. 
Dan, if I have a question related to your examples where is the best place to ask?  Should I ask you directly or should I post my question on forum first and send the link to you as well? Which way is more convenient for you? 

By the way, last night I discovered a repo on Kepler which sounds interesting but I cannot run it on Processing3, and then I found out you forked this repo years ago. So, I wonder whether you noticed and solved this problem? Could you point out how I can solve the problem? Thanks a lot

Kepler2012.pde line 64:
```
  getPlanets(sketchPath + "/data/KeplerData.csv", false);
  println(planets.size());
  getPlanets(sketchPath + "/data/planets2012_2.csv", true);
  println(planets.size());
```
error: 
```
The field PConstants.OPENGL is depreciated      line 55
The field PApplet.sketchPath is not visible            line 64
The field PApplet.sketchPath is not visible             line 66
```

**Comment by shiffman** [comment]
Hi Kenny,

For general programming questions about the examples, yes the forum is the best place and you can send me the link.  Github is absolutely fine as well, but I would prefer to try to keep the discussion here more related to example fixes, etc.

Re: Kepler, I updated my fork to be 3.0 compatible.

**Comment by EmbraceLife** [comment]
Great! Thanks Dan, I know what to do now.

**Comment by EmbraceLife** [comment]
Thanks a lot for updating Kepler

**Pull request merged**
